# Generated by Django 3.1.2 on 2020-12-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchStats',
            new_name='Match_Stats',
        ),
        migrations.RenameModel(
            old_name='TourneyLevel',
            new_name='Player_Entry',
        ),
        migrations.RenameModel(
            old_name='PlayerEntry',
            new_name='Tourney_Level',
        ),
    ]
