# Generated by Django 3.1.2 on 2020-12-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20201201_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_stats',
            name='player_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.player_entry'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='tourney_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.tourney_level'),
        ),
    ]
