# Generated by Django 3.1.2 on 2020-12-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20201201_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
