# Generated by Django 3.1.2 on 2020-12-02 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20201202_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_stats',
            name='aces',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='break_points_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='break_points_saved',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='double_faults',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='first_services',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='first_services_won',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='front.player'),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='player_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='front.player_entry'),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='rank_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='second_services_won',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='seed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='service_game_won',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match_stats',
            name='service_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
