# Generated by Django 3.1.4 on 2020-12-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20201202_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='best_of',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='minutes',
            field=models.IntegerField(null=True),
        ),
    ]
