# Generated by Django 3.1.4 on 2020-12-03 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_match_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('points', models.IntegerField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.player')),
            ],
        ),
    ]
