# Generated by Django 3.1.4 on 2020-12-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
