import uuid
from cassandra.cqlengine import columns
from django_cassandra_engine.models import DjangoCassandraModel


class TennisMatches(DjangoCassandraModel):
    tennis_match_id = columns.Integer(primary_key=True)
    tourney_id = columns.Text(min_length=0, max_length=10)
    tourney_name = columns.Text(min_length=0, max_length=50)
    draw_size = columns.Integer()
    tourney_date = columns.Date()
    match_num = columns.Integer()
    winner_id = columns.Integer()
    winner_seed = columns.Float()
    winner_name = columns.Text(max_length=100)
    winner_ht = columns.Float()
    winner_ioc = columns.Text()
    winner_age = columns.Integer()
    loser_id = columns.Integer()
    loser_seed = columns.Float()
    loser_name = columns.Text(max_length=100)
    loser_ht = columns.Float()
    loser_ioc = columns.Text()
    loser_age = columns.Integer()
    score = columns.Text(max_length=100)
    best_of = columns.Integer()
    round = columns.Text(max_length=10)
    minutes = columns.Float()
    w_ace = columns.Integer()
    w_df = columns.Integer()
    w_svpt = columns.Integer()
    w_1st_in = columns.Integer()
    w_1st_won = columns.Integer()
    w_2nd_won = columns.Integer()
    w_sv_gms = columns.Integer()
    w_bp_saved = columns.Integer()
    w_bp_faced = columns.Integer()
    l_ace = columns.Integer()
    l_df = columns.Integer()
    l_svpt = columns.Integer()
    l_1st_in = columns.Integer()
    l_1st_won = columns.Integer()
    l_2nd_won = columns.Integer()
    l_sv_gms = columns.Integer()
    l_bp_saved = columns.Integer()
    l_bp_faced = columns.Integer()
    winner_rank = columns.Integer()
    winner_rank_points = columns.Integer()
    loser_rank = columns.Integer()
    loser_rank_points = columns.Integer()
    created_at = columns.DateTime()
    updated_at = columns.DateTime()